# Generated by Django 5.0.3 on 2024-03-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
